chore(zephyr): upgrade to Zephyr v3.7.0
TODO: hitting some crypto lib build errors :(

```
[4/608] Generating include/generated/zephyr/version.h
-- Zephyr version: 3.7.0 (/Users/gminnehan/projects/zephyr-esp32-workspace/zephyr), build: v3.7.0
[183/608] Building C object zephyr/CMakeFiles/zephyr.dir/Users/gminnehan/projects/zephyr-esp32-workspace/modules/hal/espressif/components/wpa_supplicant/src/ap/wpa_auth.c.obj
/Users/gminnehan/projects/zephyr-esp32-workspace/modules/hal/espressif/components/wpa_supplicant/src/ap/wpa_auth.c: In function '__wpa_send_eapol':
/Users/gminnehan/projects/zephyr-esp32-workspace/modules/hal/espressif/components/wpa_supplicant/src/ap/wpa_auth.c:1131:13: warning: implicit declaration of function 'rc4_skip' [-Wimplicit-function-declaration]
 1131 |             rc4_skip(ek, 32, 256, (u8 *) (key + 1), key_data_len);
      |             ^~~~~~~~
```