Esp32s3-devkitm board was removed (consolidated) in zephyr 4.4 (#28)
There's still a build error on esp32c3, which I am fixing in the
Memfault SDK:

```bash
undefined reference to `rv_utils_dbgr_is_attached'
```